[2025-07-03T04:03:04.732+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.send_email manual__2025-07-03T04:02:44+00:00 [queued]>
[2025-07-03T04:03:04.738+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.send_email manual__2025-07-03T04:02:44+00:00 [queued]>
[2025-07-03T04:03:04.738+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-07-03T04:03:04.738+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-07-03T04:03:04.738+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-07-03T04:03:04.745+0000] {taskinstance.py:1300} INFO - Executing <Task(EmailOperator): send_email> on 2025-07-03 04:02:44+00:00
[2025-07-03T04:03:04.747+0000] {standard_task_runner.py:55} INFO - Started process 4344 to run task
[2025-07-03T04:03:04.749+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'send_email', 'manual__2025-07-03T04:02:44+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/email_dag.py', '--cfg-path', '/tmp/tmpe9l_sybv']
[2025-07-03T04:03:04.750+0000] {standard_task_runner.py:83} INFO - Job 85: Subtask send_email
[2025-07-03T04:03:04.798+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.send_email manual__2025-07-03T04:02:44+00:00 [running]> on host a5fcee7378f1
[2025-07-03T04:03:04.836+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=aws@evoluth.com.br
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2025-07-03T04:02:44+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-03T04:02:44+00:00
[2025-07-03T04:03:04.842+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-07-03T04:03:04.842+0000] {email.py:268} INFO - Email alerting: attempt 1
[2025-07-03T04:03:06.100+0000] {email.py:280} INFO - Sent an alert email to ['aws@evoluth.com.br']
[2025-07-03T04:03:07.759+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=email_test, task_id=send_email, execution_date=20250703T040244, start_date=20250703T040304, end_date=20250703T040307
[2025-07-03T04:03:07.781+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-07-03T04:03:07.793+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
